GET http://localhost:3004/ 


#######

POST http://localhost:3004/
Content-Type: application/json

{
    "isChecked": true ,
    "work": "Learn PHP"
}

#########


DELETE http://localhost:3004/todo/22


#######

DELETE http://localhost:3004/delete/all


#######

PUT http://localhost:3004/todo/28?isChecked=true


######

GET http://localhost:3004/bookmark

#########

POST http://localhost:3004/bookmark
Content-Type: application/json 

{
    "webLogo":
      "https://dashboard.render.com/web/srv-ckbctb6smu8c739bd1a0/jobs",
    "url": "https://dashboard.render.com/web/srv-ckbctb6smu8c739bd1a0/jobs",
    "displayText": "Render backend Publisher"
}

###########


DELETE http://localhost:3004/bookmark/del/9


###########

GET http://localhost:3004/check/pass/my 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG5uYmpqZGQiLCJ1c2VyX2lkIjoxNCwiaWF0IjoxNjk2MTQ2NjAxfQ.6RIvR0TeROy7ElBNiMwdVFUjD7uwnnpdfuXlylq23Bs

###########

POST http://localhost:3004/register/
Content-Type:  application/json 

{
  "username": "tejas",
  "password": "tejas1234",
  "mobileNo": 7895441429,
  "dob": "08-08-2003"
}



###########

POST http://localhost:3004/login
Content-Type:  application/json 

{
  "username": "Johnnbjjdd",
  "password": "tejas1234"
}